### ISSUE TITLE
[BUG] Logging formatting breaks after errors

### ISSUE THREAD

**Issue by afal007** [mage-ai/mage-ai#4774] opened 2024-03-17 08:35 UTC
### Mage version

master branch

### Describe the bug

If used default plaintext logging format it can change to other confusing format after errors. I couldn't identify if it is happening after any error or just after error from this bug - https://github.com/mage-ai/mage-ai/issues/4773. Example will be in screenshots.

PS 
First I thought it could be bacause of my PR - https://github.com/mage-ai/mage-ai/pull/4772
Double checked it on master branch - it persists

### To reproduce

1. Reproduce https://github.com/mage-ai/mage-ai/issues/4773
2. Check logs

### Expected behavior

Logs formatting is persistent

### Screenshots

**Was:**
![Screenshot 2024-03-16 at 23 22 59](https://github.com/mage-ai/mage-ai/assets/10331336/7f95b5e2-7509-4d5b-9154-fc948e0ea801)

**Became:**
![Screenshot 2024-03-16 at 23 25 37](https://github.com/mage-ai/mage-ai/assets/10331336/5f403a37-8422-4adb-8a94-bf0add2fc510)

### Operating system

- OS client: MacOS Sonoma 14.4
- OS server: Ubuntu 22.04 LTS
- Browser client: Google Chrome Version 122.0.6261.129 (Official Build) (arm64)

**Comment by wangxiaoyou1993** [comment] 2024-03-19 21:51
@afal007 i don't quite get your issue. can you elaborate on that?

**Comment by afal007** [comment] 2024-03-21 17:41
@wangxiaoyou1993 Logging formats are changing by themselves. You can see it in screenshots. Both screenshots are taken in single container run. It wasn't restarted or anything like that.

1 screenshot - formatted as `%(asctime)s\t[%(name)25.25s]\t%(levelname)5s: %(message)s`
2 screenshot - formatted as `%(levelname) %(message)`

In my case it changes after the error I described in another bug that I attached. I am not sure if it works like this only in this error case or after any error. But it is really annoying - I sometimes looking into logs to debug problems and this formatting it is changing into is just impossible - no indentation and timestamps.

**Comment by dy46** [comment] 2024-04-08 18:06
hey @afal007, this issue should be resolved in the next version of Mage. the issue is caused by one of Mage's dependencies, so you should be able to resolve the issue by upgrading the dependency as well.
```
pip3 install -U "git+https://github.com/mage-ai/singer-python.git#egg=singer-python"
```

**Closed by dy46** 2024-04-08 18:06 UTC
Labels: bug
