### ISSUE TITLE
Access denied after changing default login credentials

### ISSUE THREAD

**Issue by aggelito** [mage-ai/mage-ai#3896] opened 2023-11-03 10:10 UTC
**Describe the bug**
When enabling REQUIRE_USER_AUTHENTICATION=1 and logging in with the default admin account and updating user email and password, I get the error saying "You don't have access to this project". 

**To Reproduce**
1. Create a project with REQUIRE_USER_AUTHENTICATION=0
2. Change REQUIRE_USER_AUTHENTICATION=1 and restart docker.
3. Log in
4. Update admin email and password
5. See error
![image (2)](https://github.com/mage-ai/mage-ai/assets/6872516/b1438f11-45a0-4732-b75e-dd546563ae21)

**Expected behavior**
Be able to login and update the default admin user credentials

**Desktop (please complete the following information):**
 - Ubuntu server
 - Docker setup
 - Mage v0.9.41 

**Additional context**
Only updating the password works. It's changing the email that's the problem.
Let me know if you need more information :pray:

**Comment by aggelito** [comment] 2023-11-03 10:26
guess it's not a really serious issue.. it works just creating a new owner account

**Comment by wangxiaoyou1993** [comment] 2023-11-08 23:47
@aggelito how do you change the admin email? that field is not editable?
<img width="831" alt="image" src="https://github.com/mage-ai/mage-ai/assets/80284865/69060137-50c1-46b0-8e03-5bfdfdb8fb58">

**Comment by wangxiaoyou1993** [comment] 2023-11-13 22:53
Close this issue since we can't reproduce it. Feel free to reopen if you still have this issue.

**Closed by wangxiaoyou1993** 2023-11-13 22:53 UTC

**Comment by aggelito** [comment] 2023-11-14 10:34
> @aggelito how do you change the admin email? that field is not editable? <img alt="image" width="831" src="https://user-images.githubusercontent.com/80284865/281572988-69060137-50c1-46b0-8e03-5bfdfdb8fb58.png">

Seems like it's been changed in recent updates :thinking: Thanks for looking, you guys rock!
