### ISSUE TITLE
DuckDB SQL blocks cannot accept GCP paths

### ISSUE THREAD

**Issue by mattppal** [mage-ai/mage-ai#3722] opened 2023-10-10 17:13 UTC
When using a SQL block with the duckdb engine, it defaults to Amazon's S3 (as shown in the 1st image). However, with the same configuration, a Python block fetches data from the GCP storage bucket (as shown in the 2nd image), though there are some Spark warnings.

https://mageai.slack.com/archives/C03HTTWFEKE/p1696589199856649

![image](https://github.com/mage-ai/mage-ai/assets/59450879/0d1ba4d4-6885-42fb-b80d-96900be88f5b)

![image](https://github.com/mage-ai/mage-ai/assets/59450879/ed4b31c0-e422-4d7c-a8ea-444ede97f6f7)

**Comment by matrixstone** [comment] 2023-11-12 21:16
Hi Matt, thank you for reporting the issue!
I tried to reproduce it, however I am able to successfully retrieve the parquet from GCS(Google Cloud Storage).
Here is the code I am using:
![input](https://github.com/mage-ai/mage-ai/assets/5386254/869f86a6-302b-4687-b1b2-42635400922f)

The is the output I got:
![output](https://github.com/mage-ai/mage-ai/assets/5386254/ef34f72c-f1ca-4ab5-866b-16cda7c34fba)

I didn't find much difference between our code. Do you want to try again or try to use my code see if that works on your end?

**Comment by mattppal** [comment] 2023-11-13 19:03
@matrixstone thanks— I created this issue on behalf of a user from slack. I'll ping them to see what the issue is.

**Comment by wangxiaoyou1993** [comment] 2024-01-17 23:01
Close this issue since there's no followup.

**Closed by wangxiaoyou1993** 2024-01-17 23:01 UTC
Labels: bug
