### ISSUE TITLE
[BUG] : initial status checks doesn't account for lack of jobs/scheduler..

### ISSUE THREAD

**Issue by dkwolfe4** [mage-ai/mage-ai#4981] opened 2024-04-23 23:53 UTC
### Mage version

mage-ai-0.8.43 

### Describe the bug

Installed via conda.  Launched and immediately started throwing errors into the log file it appears that job_manager.clean_up_jobs() isn't designed to handle the initial startup state where no  run scheduler exists... and fails with AttributeError: NoneType

From the log files:

INFO:mage_ai.orchestration.pipeline_scheduler_original:Active pipeline runs: []
ERROR:mage_ai.server.scheduler_manager:Failed to run scheduler.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/mage_ai/server/scheduler_manager.py", line 53, in run_scheduler
    LoopTimeTrigger().start()
  File "/opt/anaconda3/lib/python3.11/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py", line 14, in start
    self.run()
  File "/opt/anaconda3/lib/python3.11/site-packages/mage_ai/orchestration/triggers/time_trigger.py", line 11, in run
    schedule_all()
  File "/opt/anaconda3/lib/python3.11/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py", line 1659, in schedule_all
    job_manager.clean_up_jobs()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'clean_up_jobs'

### To reproduce

do clean install,
view log.
error message repeats every approx 30 seconds

Note: this could be the result of a flawed install...  did not try to reproduce.

### Expected behavior

expected install to just work and capable of handling initial state of no jobs available.

### Operating system

macOS Sonoma/ 14.4.1 Safar/ 17.4.1 MBP3

**Comment by vimalnar** [comment] 2024-04-26 03:14
I had the same issue, here is a comment from "Xiaoyou Wang" on Slack:

"The issue is fixed and will be included in 0.9.70
You can use 0.9.68 for now"

I downgraded my version which worked right away...

**Comment by wangxiaoyou1993** [comment] 2024-04-30 21:56
The version 0.9.70 is published with the fix for this issue.

**Closed by wangxiaoyou1993** 2024-04-30 21:56 UTC
Labels: bug
