### ISSUE TITLE
Monaco Editor Failure due to CDN Outage

### ISSUE THREAD

**Issue by halidrauf** [mage-ai/mage-ai#2776] opened 2023-06-10 00:45 UTC
**Describe the bug**
The Monaco loader fails to load as JSDeliver Servers are offline

**To Reproduce**
Clear Cache and Cookies
Install Mage.Ai Into a Dockker Container
Try to load the editor page for a pipeline
Editor would fail to load as JSDeliver is down
![image](https://github.com/mage-ai/mage-ai/assets/21981974/867147b7-826b-451b-8b61-3e00100156f6)

**Expected behavior**
The editor would load each block

**Screenshots**

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
Switch from JSDeliver to https://cdnjs.com/libraries/monaco-editor
![image](https://github.com/mage-ai/mage-ai/assets/21981974/9ceac6f6-0fac-4240-bbe6-a9aa6d881b5b)

**Comment by tommydangerous** [comment] 2023-06-10 20:10
Is this still happening to you?

**Comment by tommydangerous** [comment] 2023-06-11 23:01
Does this page work for you? https://demo.mage.ai/pipelines/divine_night/edit?sideview=tree

**Comment by johnson-mage** [comment] 2023-06-19 19:25
@halidrauf Are you still having issues loading the Monaco Editor? If you are, I'm wondering if it's unrelated to the CDN. I saw in your screenshot that `jsdelivr.net` was down, but I believe the jsdelivr.net CDN is `cdn.jsdelivr.net`, which is not down. 

I created a PR (https://github.com/mage-ai/mage-ai/pull/2821) which shows how we could update the CDN, but that doesn't seem necessary right now if the issue is unrelated to the CDN being down. Please DM me on our Slack channel (mage.ai/chat) if you need further help with troubleshooting.

<img width="538" alt="image" src="https://github.com/mage-ai/mage-ai/assets/78053898/8233b2c4-9e8a-4a63-afd4-b529f81df263">

**Comment by johnson-mage** [comment] 2023-06-20 17:56
> At the moment it seems that Jsdelivr is being blocked in certain regions. I am using Cloudflare's WARP to use Mage.ai

@halidrauf Got it. Thanks for the update. We will keep this in mind if other users run into a similar issue. Going to close this github issue now since the CDN being blocked seems like a separate issue, and is non-blocking. Feel free to open a new github issue if you need, though.

**Closed by johnson-mage** 2023-06-20 17:56 UTC

**Comment by farmboy-dev** [comment] 2023-10-19 22:04
@tommydangerous @johnson-mage I have the same issue on a private network, so can't connect to that cdn server. Is there a workaround?

**Comment by johnson-mage** [comment] 2023-10-20 00:26
> I have the same issue on a private network, so can't connect to that cdn server. Is there a workaround?

@farmboy-dev Replying here for posterity, but per our discussion in Slack, you can try using https://1.1.1.1/ (a free cloudflare dns resolver). If you are working off a forked repo of Mage and can modify the source code, you can try uncommenting these [lines](https://github.com/mage-ai/mage-ai/blob/master/mage_ai/frontend/components/CodeEditor/index.tsx#L15-L19) to load the editor from a different cdn (cloudflare). We will work on including the editor in our build so it doesn’t need to be loaded from a cdn in an upcoming release.

**Comment by johnson-mage** [comment] 2023-11-13 19:26
> > I have the same issue on a private network, so can't connect to that cdn server. Is there a workaround?
> 
> @farmboy-dev Replying here for posterity, but per our discussion in Slack, you can try using https://1.1.1.1/ (a free cloudflare dns resolver). If you are working off a forked repo of Mage and can modify the source code, you can try uncommenting these [lines](https://github.com/mage-ai/mage-ai/blob/master/mage_ai/frontend/components/CodeEditor/index.tsx#L15-L19) to load the editor from a different cdn (cloudflare). We will work on including the editor in our build so it doesn’t need to be loaded from a cdn in an upcoming release.

@farmboy-dev Please update Mage to v0.9.44 and try loading the code editor again. We made an update to load the Monaco Editor without fetching from CDN: https://github.com/mage-ai/mage-ai/pull/3916.
