### ISSUE TITLE
Data integration in batch pipeline: Incremental fetch fails when using date column type as bookmark key in Oracle

### ISSUE THREAD

**Issue by jmanoharan98** [mage-ai/mage-ai#4596] opened 2024-02-17 10:17 UTC
### Mage version

0.9.64

### Describe the bug

I'm encountering an issue with the Data integration in batch pipeline functionality while fetching records from an Oracle database in incremental mode. The bookmark key used for incremental fetching is currently a date type, which seems to be causing an error. When I change the bookmark key to a number data type column, everything works as expected.

"error_stacktrace": ["INFO [2024-02-16T09:31:03.928126] {\"caller\": \"OracleDB\", \"level\": \"INFO\", \"message\": \"Process started.\", \"tags\": {}, \"timestamp\": 1708075863, \"uuid\": \"4ba8a97e1d204aaa943f3227bd9cdfef\", \"type\": \"LOG\"}\nINFO [2024-02-16T09:31:03.928486] {\"caller\": \"OracleDB\", \"level\": \"INFO\", \"message\": \"Counting records for TABLE_1 started.\", \"tags\": {\"stream\": \"TABLE_1\"}, \"timestamp\": 1708075863, \"uuid\": \"8a86c3a9d6e646e9b3a62f8b74dfd098\", \"type\": \"LOG\"}\nERROR [2024-02-16T09:31:04.184584] {\"caller\": \"OracleDB\", \"level\": \"EXCEPTION\", \"message\": \"OracleDB process failed with error ORA-00906: missing left parenthesis.\", \"tags\": {\"error\": \"ORA-00906: missing left parenthesis\", \"errors\": [\"  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/oracledb/__init__.py\\\", line 105, in <module>\\n    main(OracleDB)\\n\", \"  File \\\"/usr/local/lib/python3.10/site-packages/singer/utils.py\\\", line 235, in wrapped\\n    return fnc(*args, **kwargs)\\n\", \"  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\\\", line 729, in main\\n    source.process()\\n\", \"  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\\\", line 281, in process\\n    errors=traceback.format_stack(),\\n\"], \"message\": \"Traceback (most recent call last):\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\\\", line 238, in process\\n    count = self.count_records(\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\\\", line 166, in count_records\\n    rows, rows_temp = self.__fetch_rows(\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/sql/base.py\\\", line 414, in __fetch_rows\\n    rows_temp = self.build_connection().load(with_limit_query_string)\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\\\", line 94, in load\\n    data = self.execute([\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\\\", line 46, in execute\\n    data = self.execute_with_connection(connection, query_strings)\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\\\", line 16, in execute_with_connection\\n    return self.get_data_from_query_strings(cursor, query_strings)\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\\\", line 82, in get_data_from_query_strings\\n    raise err\\n  File \\\"/usr/local/lib/python3.10/site-packages/mage_integrations/connections/sql/base.py\\\", line 75, in get_data_from_query_strings\\n    cursor.execute(clean_query(query_string))\\n  File \\\"/usr/local/lib/python3.10/site-packages/oracledb/cursor.py\\\", line 378, in execute\\n    impl.execute(self)\\n  File \\\"src/oracledb/impl/thin/cursor.pyx\\\", line 138, in oracledb.thin_impl.ThinCursorImpl.execute\\n  File \\\"src/oracledb/impl/thin/protocol.pyx\\\", line 382, in oracledb.thin_impl.Protocol._process_single_message\\n  File \\\"src/oracledb/impl/thin/protocol.pyx\\\", line 383, in oracledb.thin_impl.Protocol._process_single_message\\n  File \\\"src/oracledb/impl/thin/protocol.pyx\\\", line 376, in oracledb.thin_impl.Protocol._process_message\\noracledb.exceptions.DatabaseError: ORA-00906: missing left parenthesis\\n\"}, \"timestamp\": 1708075864, \"uuid\": \"f2f3279df3274490a277967e8bbedaaf\", \"type\": \"LOG\"} 

### To reproduce

1) Enable the Data integration in batch pipeline feature
![image](https://github.com/mage-ai/mage-ai/assets/70794479/2c92d89a-5b2a-4996-ae9f-963d4a674408)
2) Create a standard(batch) pipeline
3) Create an oracle data loader block
![image](https://github.com/mage-ai/mage-ai/assets/70794479/6e5a5ee2-d557-49f8-be2d-f74af31812ac)
4) Configure stream, select a table and in the setting select replication method as incremental
![image](https://github.com/mage-ai/mage-ai/assets/70794479/45b3524a-de78-4aa2-ae42-b98ba436346c)
5) Select needed columns but select a date type column as Bookmark 
![image](https://github.com/mage-ai/mage-ai/assets/70794479/bde2f0c9-3710-4178-b88a-a3e9f2b438cc)
6) Create a local file data exporter block
7) Execute the pipeline. First time the pipeline will run successfully, but in the next runs it will fail with the error mentioned in the description.
![image](https://github.com/mage-ai/mage-ai/assets/70794479/ac205c3e-8e1c-4eed-a36e-97bda02fa2fb)

### Expected behavior

The Incremental run should be successful and incremental fetch of the data based on the bookmark date column should happen.

### Operating system

- OS  Ubuntu 22.04.3 LTS

### Additional context

1. This issue occurred if the bookmark column data type is datetime/string. I tested with the numeric bookmark column, its seems working as expected without any failure.
2. The error in occurring in count_records function and I noticed that if we select bookmark column as numeric this function does not get triggered.

**Comment by matrixstone** [comment] 2024-03-23 07:54
Hi @jmanoharan98 , I found the issue is caused by when using incremental with datetime as bookmark, the query to fetch latest records failed. That is due to datetime is not constructed properly in the where clause. I implement a fix FYI.

**Comment by matrixstone** [comment] 2024-04-01 21:52
Fixed by PR: https://github.com/mage-ai/mage-ai/pull/4816

**Closed** 2024-04-01 21:52 UTC
Labels: bug
