### ISSUE TITLE
Сan't manage users and permissions in the interface

### ISSUE THREAD

**Issue by mrykin** [mage-ai/mage-ai#4211] opened 2023-12-18 20:26 UTC
**Describe the bug**
When trying to create a user, an error occurs.
![image](https://github.com/mage-ai/mage-ai/assets/13833432/f188353a-6772-457b-a25f-b21fa898ebb0)

Text of error:
```
(sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT anon_1.permission_access AS anon_1_permission_access, anon_1.permission_created_at AS anon_1_permission_created_at, anon_1.permission_entity AS anon_1_permission_entity, anon_1.permission_entity_id AS anon_1_permission_entity_id, anon_1.permission_entity_name AS anon_1_permission_entity_name, anon_1.permission_entity_type AS anon_1_permission_entity_type, anon_1.permission_id AS anon_1_permission_id, anon_1.permission_options AS anon_1_permission_options, anon_1.permission_role_id AS anon_1_permission_role_id, anon_1.permission_updated_at AS anon_1_permission_updated_at, anon_1.user_role_user_id AS anon_1_user_role_user_id, anon_1.row_number AS anon_1_row_number 
FROM (SELECT permission.access AS permission_access, permission.created_at AS permission_created_at, permission.entity AS permission_entity, permission.entity_id AS permission_entity_id, permission.entity_name AS permission_entity_name, permission.entity_type AS permission_entity_type, permission.id AS permission_id, permission.options AS permission_options, permission.role_id AS permission_role_id, permission.updated_at AS permission_updated_at, user_role.user_id AS user_role_user_id, row_number() OVER (PARTITION BY permission.id ORDER BY user_role.id ASC) AS row_number 
FROM permission JOIN role_permission ON role_permission.permission_id = permission.id JOIN role ON role.id = role_permission.role_id JOIN user_role ON user_role.role_id = role.id AND user_role.user_id IN (?)) AS anon_1 
WHERE anon_1.row_number = ?]
[parameters: (9, 1)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

The user is created, but no changes can be made.

When you click on a user in the list, a blank page opens.
![image](https://github.com/mage-ai/mage-ai/assets/13833432/db625210-fabb-436a-b1f9-d09fb2ab5469)

Similar behavior is observed on the Permissions tab
![Запись экрана 2023-12-18 в 23 13 17](https://github.com/mage-ai/mage-ai/assets/13833432/a245a2b1-1b42-40ca-adad-0d00ee4be041)

**To Reproduce**
1. Go to settings
2. Click on 'Users'
3. Click on User on list

Same way for Permissions 
1. Go to settings
2. Click on 'Permissions'
3. click on one of Permissions

**Expected behavior**
On another server I can manage users. And I try change env/users/reinstal - this not help me.

**Server:**
 - OS: Ubuntu 18.04.6 LTS
 - venv
 - python 3.10.13
 - mage 0.9.55

**Browser:**
 - Device: Mac M1
 - OS: Ventura 13.2.1
 - Browser Chrome
 - Version 119.0.6045.199

**What I tried to do:**
- Reinstall everything in another venv
- Change user and grant rights to all folders and files to this user, which stores venv and pipelines
- Delete the database from the user folder
- Substitute a database from another working project (from another server)

As a result, for the new client I had to manually add rights via datagrip

**Comment by tommydangerous** [comment] 2023-12-18 20:43
Will try to reproduce

**Comment by tommydangerous** [comment] 2023-12-18 20:44
What environment variables did you enable to turn it on?

**Comment by mrykin** [comment] 2023-12-18 20:51
export PATH="/opt/mage/bin/python3.10:/home/serveradmin/.local/bin:$PATH"
export REQUIRE_USER_AUTHENTICATION=1
export ULIMIT_NO_FILE=81920
export USER_CODE_PATH="/opt/*****/"
HIDE_ENV_VAR_VALUES=1
MAGE_PUBLIC_HOST="http://mysite****.net:6789/"
exec mage start my_project

I start this with bash by systemmd

and I try start only for command in env - mage start my_project - same result

**Comment by mrykin** [comment] 2023-12-19 06:10
No error, when open Users, response code 304 or 200
**Users**
![image](https://github.com/mage-ai/mage-ai/assets/13833432/cdccaf4d-28fb-40ae-8dbb-c74f25942906)

**Permissions**
![image](https://github.com/mage-ai/mage-ai/assets/13833432/946515fc-76f5-4f78-afc7-e38905440044)


when i add new user
![image](https://github.com/mage-ai/mage-ai/assets/13833432/28aef8a4-9413-407e-86c9-996df59527ca)

405 code, when i try change password in profile
![image](https://github.com/mage-ai/mage-ai/assets/13833432/55542c6c-64c6-4543-a2a0-8755e9069b35)

Method not allowed
![image](https://github.com/mage-ai/mage-ai/assets/13833432/ebe66ec8-0ea2-4d97-9eab-b1a369cd5b76)

**Comment by mrykin** [comment] 2023-12-23 13:44
Any ideas?

**Comment by tommydangerous** [comment] 2023-12-25 08:12
Hello, so sorry for the delay. Can you hop in our Slack and can we do a screen share?

**Comment by mrykin** [comment] 2023-12-25 08:30
Sorry, I don't have a slack account. I need you to add me or we can contact via zoom, skype, telegram.

**Comment by tommydangerous** [comment] 2023-12-25 16:40
I sent you an invite. If you didn’t get it, I can send another one or you can click this: https://join.slack.com/t/mageai/shared_invite/zt-1w5sv3y3n-iUOxd0dwyNY1SW~ikpevSw

**Comment by wangxiaoyou1993** [comment] 2024-01-16 22:30
Just to follow up on this ticket. Has this issue been resolved?

**Comment by wangxiaoyou1993** [comment] 2024-01-17 22:20
Close this issue since there's no followup. Feel free to reopen it if the issue is not resolved.

**Closed by wangxiaoyou1993** 2024-01-17 22:20 UTC
